main/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^facilities/$', views.FacilitiesListView.as_view(), name='facilities'),
    url(r'^facilities/(?P<pk>\d+)$',views.FacilitieDetailView.as_view(), name='facilitie-detail'),
    url(r'^clients/(?P<pk>\d+)$',views.ClientDetailView.as_view(), name='client-detail'),
    url(r'^clients/(?P<pk>\d+)/editcli/$',views.editcli, name='editcli'),
    url(r'^contracts/(?P<pk>\d+)$',views.ContractDetailView.as_view(), name='contract-detail'),
    url(r'^contracttarifs/(?P<pk>\d+)$',views.ContracttarifDetailView.as_view(), name='contracttarif-detail'),
    url(r'^services/$', views.ServicesListView.as_view(), name='services'),
    url(r'^services/(?P<pk>\d+)$',views.ServiceDetailView.as_view(), name='service-detail'),
    url(r'^networks/(?P<pk>\d+)$',views.NetworkDetailView.as_view(), name='network-detail'),
    url(r'^my_clients/$', views.MyClientsListView.as_view(), name='my_clients'),
]
# ModelForm create,update,delete
urlpatterns += [  
    url(r'^services/create/$', views.ServiceCreate.as_view(), name='service_create'),
    url(r'^services/(?P<pk>\d+)/update/$', views.ServiceUpdate.as_view(), name='service_update'),
    url(r'^services/(?P<pk>\d+)/delete/$', views.ServiceDelete.as_view(), name='service_delete'),
]
urlpatterns += [  
    url(r'^facilities/create/$', views.FacilitieCreate.as_view(), name='facilitie_create'),
    url(r'^facilities/(?P<pk>\d+)/update/$', views.FacilitieUpdate.as_view(), name='facilitie_update'),
    url(r'^facilities/(?P<pk>\d+)/delete/$', views.FacilitieDelete.as_view(), name='facilitie_delete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stat_tst/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.conf.urls import url
from django.conf.urls import include
from django.views.generic import RedirectView
urlpatterns += [
    url(r'^main/', include('main.urls')),
]

urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/main/', permanent=True)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

#from django.conf import settings
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#if settings.DEBUG:
#    urlpatterns += staticfiles_urlpatterns()

main/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User # Импорт модели пользователя
# Create your models here.
class Client(models.Model):
    description = models.CharField(max_length=100,help_text="Название организации")
    contacts = models.TextField(blank=True,null=True)
    comment = models.TextField(blank=True,null=True)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    class Meta:
        permissions = (("can_disable_cli","Set disable clients"),("can_full_view","Show owners"))
    def __str__(self):
        return self.description
    def get_absolute_url(self):
        return reverse('client-detail', args=[str(self.id)])

class Contract(models.Model):
    client = models.ForeignKey('Client',on_delete=models.SET_NULL,null=True,verbose_name="Клиент")
    email = models.EmailField(verbose_name="E-mail")
    contracttype = models.ForeignKey('ContractType',on_delete=models.SET_NULL,null=True,verbose_name="Тип договора")
    paystype = models.ForeignKey('PaysType',on_delete=models.SET_NULL,null=True)
    max_expense = models.DecimalField(max_digits=10,decimal_places=4, verbose_name="Возможное превышение расходов")
    description = models.TextField(verbose_name="Описание")
    sum_at_date = models.DecimalField(max_digits=10,decimal_places=4, verbose_name="Остаток на")
    date = models.DateField(null=True,blank=True, verbose_name="дату")
    adv_fac = models.DecimalField(max_digits=10,decimal_places=2,verbose_name="Дополнительные услуги на сумму")
    pays = models.DecimalField(max_digits=10,decimal_places=4,verbose_name="Платежи за месяц")
    epay = models.CharField(max_length=10, verbose_name="E-Pay аккаунт")
    comment = models.TextField(verbose_name="Комментарий",blank=True,null=True)
    def __str__(self):
        return str(self.client)
    def get_absolute_url(self):
        return reverse('contract-detail', args=[str(self.id)])

class ContractType(models.Model):
    contracttype = models.CharField(max_length=20,help_text="Тип договора")
    def __str__(self):
        return self.contracttype
class PaysType(models.Model):
    paystype = models.CharField(max_length=20,help_text="Тип платежей")
    def __str__(self):
        return self.paystype
VECTOR_CHOICES = (
('in',u'входящий'),
('out',u'исходящий'),
('max',u'превалирующий'),
('min',u'наименьший'),
('bw',u'условный безлимит'),
)
class Facilitie(models.Model):
    cost = models.DecimalField(max_digits=10,decimal_places=2,verbose_name="Стоимость")
    bwi = models.IntegerField(verbose_name="Скорость",help_text="0 - для безлимитов")
    mbyte = models.IntegerField(verbose_name="Мбайт",help_text="0 - для безлимитов")
    transport = models.DecimalField(max_digits=10,decimal_places=4,verbose_name="Транспорт",help_text="Помегабайтная стоимость")
    vector = models.CharField(u'Направление',max_length=10,choices=VECTOR_CHOICES,help_text="(in,out,max) - расчет по входящему, исходящему, превалирующему трафику, bw для условных безлимитов")
    mul = models.DecimalField(max_digits=10,decimal_places=2,verbose_name="Множитель")
    description = models.CharField(max_length=30,verbose_name="Описание")
    comment = models.TextField(verbose_name="Комментарии",blank=True,null=True)
    def __str__(self):
        return self.description
    def get_absolute_url(self):
        return reverse('facilitie-detail', args=[str(self.id)])


class ContractTarif(models.Model):
    contract = models.ForeignKey('Contract',on_delete=models.CASCADE,null=True,verbose_name="Договор")
    description = models.CharField(max_length=30,verbose_name="Описание тарифа")
    comment = models.TextField(verbose_name="Комментарий",blank=True,null=True)
    fid = models.ForeignKey('Facilitie',on_delete=models.SET_NULL,null=True,verbose_name="Тариф")
    sale = models.IntegerField(verbose_name="Скидка, %")
    start = models.DateField(verbose_name="Начало действия тарифа")
    stop = models.DateField(default='3000-01-01',verbose_name="Конец действия тарифа")
    def __str__(self):
        return self.description
    def get_absolute_url(self):
        return reverse('contracttarif-detail', args=[str(self.id)])

class Network(models.Model):
    tarif = models.ForeignKey('ContractTarif',on_delete=models.SET_NULL,null=True,verbose_name="Тариф")
    calculate_point = models.CharField(max_length=20,default='127.0.0.1',verbose_name="Точка обсчета")
    from_net = models.CharField(max_length=20,default='0.0.0.0/0',verbose_name="Из сети")
    to_net = models.CharField(max_length=20,verbose_name="На сеть",help_text="IP-адрес/маска")
    from_int = models.CharField(max_length=20,default='0',verbose_name="С интерфейса")
    to_int = models.CharField(max_length=20,default='0',verbose_name="На интерфейс")
    description = models.CharField(max_length=20,verbose_name="Описание")
    comment = models.TextField(blank=True,null=True,verbose_name="Комментарий")
    def __str__(self):
        return self.description
    def get_absolute_url(self):
        return reverse('network-detail', args=[str(self.id)])

# Таблица услуг
TYPE_CHOICES = (
('p',u'ежемесячный платеж'),
('s',u'разовая услуга'),
)
class Service(models.Model):
    code = models.CharField(max_length=20,verbose_name="Код")
    description = models.CharField(max_length=40,verbose_name="Описание")
    typeserv = models.CharField(u'Тип',max_length=40, choices=TYPE_CHOICES)
    cost = models.DecimalField(max_digits=10,decimal_places=4,verbose_name="Цена")
    comment = models.TextField(verbose_name="Комментарий",blank=True,null=True)
    def __str__(self):
        return self.description
    def get_absolute_url(self):
        return reverse('service-detail', args=[str(self.id)])

main/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking renewal date range.

class EditClientForm(forms.Form):
    description = forms.CharField(label="Описание",help_text="Наименование клиента")
    contacts = forms.CharField(label="Контакты")
    comment = forms.CharField(label="Комментарий")

#from django.forms import ModelForm
#from .models import Service
#class ServiceModelForm(ModelForm):
#    class Meta:
#        model = Service
#        fields = '__all__'

main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.

from .models import Client,Contract,Facilitie,Network,ContractTarif,Service

@login_required
def index(request):
    num_cli = Client.objects.all()
    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits+1
    return render(
        request,
        'index.html',
        context={'num_cli': num_cli, 'num_visits': num_visits},
    )

from .forms import EditClientForm
from django.urls import reverse

@login_required
def editcli(request,pk):
    client = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        form = EditClientForm(request.POST)
        if form.is_valid():
            client.description = form.cleaned_data['description']
            client.contacts = form.cleaned_data['contacts']
            client.comment = form.cleaned_data['comment']
            client.creator = request.user
            client.save()
            return HttpResponseRedirect(reverse('my_clients'))
    else:
        def_description = client.description
        def_contacts = client.contacts
        def_comment = client.comment
        form = EditClientForm(initial={'description': def_description, 'contacts': def_contacts, 'comment': def_comment,})
    return render(request,'main/editcli.html',{'form': form})


class ServiceCreate(CreateView):
    model = Service
    fields = '__all__'

class ServiceUpdate(UpdateView):
    model = Service
    fields = '__all__'

class ServiceDelete(DeleteView):
    model = Service
    success_url = reverse_lazy('services')

class FacilitieCreate(CreateView):
    model = Facilitie
    fields = '__all__'

class FacilitieUpdate(UpdateView):
    model = Facilitie
    fields = '__all__'

class FacilitieDelete(DeleteView):
    model = Facilitie
    success_url = reverse_lazy('facilities')





















from django.views import generic

class FacilitiesListView(LoginRequiredMixin, generic.ListView):
    model = Facilitie

class MyClientsListView(LoginRequiredMixin, generic.ListView):
    model = Client
    template_name = 'main/my_clients_listview.html'
    paginate_by = 10
    def get_queryset(self):
        return Client.objects.filter(creator=self.request.user).order_by('description')

class ServicesListView(LoginRequiredMixin, generic.ListView):
    model = Service

class ServiceDetailView(LoginRequiredMixin, generic.DetailView):
    model = Service

class ClientDetailView(LoginRequiredMixin, generic.DetailView):
    model = Client

class ContractDetailView(LoginRequiredMixin, generic.DetailView):
    model = Contract

class ContracttarifDetailView(LoginRequiredMixin, generic.DetailView):
    model = ContractTarif

class NetworkDetailView(LoginRequiredMixin, generic.DetailView):
    model = Network

class FacilitieDetailView(LoginRequiredMixin, generic.DetailView):
    model = Facilitie

main/templates/main/client_detail.html
{% extends "base_generic.html" %}

{% block title %}
<title>Информация о клиенте</title>
{% endblock %}
{% block content %}
<h1>Клиент {{ client.description }}</h1>
<p><b>Контакты:</b> {{ client.contacts }}</p>
<p><b>Комментарий:</b> {{ client.comment }}</p>
<hr>
<div style="margin-left: 20px; margin-top: 20px">
    <h4>Контракты:</h4>
    {% for acc in client.contract_set.all %}
    <p><b>Login:</b><a href='{{ acc.get_absolute_url }}'> {{ acc.description }}<br>
    {% endfor %}
    {% if perms.main.can_edit_cli %}
    <br>
    <a href="{{ client.get_absolute_url }}/editcli">Редактировать</a>
    {% endif %}
</div>
{% endblock %}

main/templates/main/contract_detail.html
{% extends "base_generic.html" %}

{% block title %} <title>Контракт</title> {% endblock %}

{% block content %}
<h2>Клиент {{ contract.client }}</h2>
<table class="table">
<tr><td>E-mail</td><td>{{ contract.email }}</td></tr>
<tr><td>Тип контракта</td><td>{{ contract.contracttype }}</td></tr>
<tr><td>Тип платежа</td><td>{{ contract.paystype }}</td></tr>
<tr><td>Возможное превышение расходов</td><td>{{ contract.max_expense }}</td></tr>
<tr><td>Описание</td><td>{{ contract.description }}</td></tr>
<tr><td>Остаток</td><td>{{ contract.sum_at_date }}</td></tr>
<tr><td>на дату</td><td>{{ contract.date }}</td></tr>
<tr><td>Дополнительные услуги на сумму</td><td>{{ contract.adv_fac }}</td></tr>
<tr><td>E-pay аккаунт</td><td>{{ contract.epay }}</td></tr>
<tr><td>Комментарий</td><td>{{ contract.comment }}</td></tr>
</table>
<hr>
<div style="margin-left: 20px; margin-top: 20px">
    <h4>Услуги по контракту:</h4>
    {% for acc in contract.contracttarif_set.all %}
    <p><b>Тариф </b><a href='{{ acc.get_absolute_url }}'> {{ acc.description }}<br>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/contracttarif_detail.html
{% extends "base_generic.html" %}

{% block title %}
<title>Информация о клиенте</title>
{% endblock %}
{% block content %}
<h1>Договор {{ contracttarif.contract }}</h1>
<p><b>Описание </b> {{ contracttarif.description }}</p>
<p><b>Комментарий </b> {{ contracttarif.comment }}</p>
<p><b>Тариф </b> {{ contracttarif.fid }}</p>
<p><b>Скидка </b> {{ contracttarif.sale }}</p>
<p><b>Начало действия тарифа </b> {{ contracttarif.start }}</p>
<p><b>Окончание действия тарифа </b> {{ contracttarif.stop }}</p>

<hr>
<div style="margin-left: 20px; margin-top: 20px">
    <h4>Сети:</h4>
    {% for acc in contracttarif.network_set.all %}
    <p><a href='{{ acc.get_absolute_url }}'> {{ acc.to_net }}<br>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/editcli.html
{% extends "base_generic.html" %}
{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

main/templates/main/facilitie_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Facilitie</h1>

<p>Are you sure you want to delete the facilitie: {{ facilitie }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

main/templates/main/facilitie_detail.html
{% extends "base_generic.html" %}

{% block title %}
<title>Информация о клиенте</title>
{% endblock %}
{% block content %}

<table class="table table-bordered table-sm">
<tr><td>Описание</td><td>{{ facilitie.description }}</td></tr>
<tr><td>Стоимость</td><td>{{ facilitie.cost }}</td></tr>
<tr><td>Скорость (Мбит/с)</td><td>{{ facilitie.bwi }}</td></tr>
<tr><td>Траффик (Мбайт)</td><td>{{ facilitie.mbyte }}</td></tr>
<tr><td>Транспорт</td><td>{{ facilitie.transport }}</td></tr>
<tr><td>Направление</td><td>{{ facilitie.vector }}</td></tr>
<tr><td>Множитель</td><td>{{ facilitie.mul }}</td></tr>
<tr><td>Комментарии</td><td>{{ facilitie.comment }}</td></tr>
</table>
{% if perms.main.can_upd_fac %}
<br>
<a href="{{ facilitie.get_absolute_url }}/update">Update</a>
{% endif %}
{% if perms.main.can_del_fac%}
<br>
<a href="{{ facilitie.get_absolute_url }}/delete">Delete</a>
{% endif %}

{% endblock %}

main/templates/main/facilitie_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

main/templates/main/facilitie_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Facilitie List</h1>

    {% if facilitie_list %}
    <ul>

      {% for fac in facilitie_list %}
      <li>
        <a href="{{ fac.get_absolute_url }}">{{ fac.description }}</a> ({{fac.cost}})
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>Facilities table is empty.</p>
    {% endif %}
    {% if perms.main.can_add_fac %}
    <a href="{% url 'facilities' %}create">Add facilitie</a>
    {% endif %}

{% endblock %}

main/templates/main/my_clients_listview.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My clients:</h1>

    {% if client_list %}
    <ul>

      {% for cli in client_list %} 
        <a href="{{cli.get_absolute_url}}">{{cli.description}}</a><br>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Клиенты отсутствуют.</p>
    {% endif %}       
    {% if perms.client.can_disable_cli %}
    <p> user {{ user.get_username }} might set disable</p>
    {% endif %}
{% endblock %}

main/templates/main/network_detail.html
{% extends "base_generic.html" %}

{% block title %}
<title>Информация о подсети</title>
{% endblock %}
{% block content %}
<h1>Тариф {{ network.tarif }}</h1>
<p><b>Точка обсчета</b> {{ network.calculate_point }}</p>
<p><b>Из сети</b> {{ network.from_net }}</p>
<p><b>На сеть</b> {{ network.to_net }}</p>
<p><b>Из интерфейса</b> {{ network.from_int }}</p>
<p><b>На интерфейс</b> {{ network.to_int }}</p>
<p><b>Описание</b> {{ network.description }}</p>
<p><b>Комментарий</b> {{ network.comment }}</p>
<hr>
{% endblock %}

main/templates/main/service_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

main/templates/main/service_detail.html
{% extends "base_generic.html" %}

{% block title %}
<title>Информация об услуге</title>
{% endblock %}
{% block content %}

<table class="table table-bordered table-sm">
<tr><td>Код</td><td>{{ service.code }}</td></tr>
<tr><td>Описание</td><td>{{ service.description }}</td></tr>
<tr><td>Тип сервиса</td><td>{{ service.typeserv }}</td></tr>
<tr><td>Цена</td><td>{{ service.cost }}</td></tr>
<tr><td>Комментарии</td><td>{{ service.comment }}</td></tr>
</table>
<br>
{% if perms.main.can_update_service %}
<a href="{{ service.get_absolute_url }}/update">update</a>
{% endif %}
<br>
{% if perms.main.can_remove_service %}
<a href="{{ service.get_absolute_url }}/delete">delete</a>
{% endif %}

{% endblock %}

main/templates/main/service_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

main/templates/main/service_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Service List</h1>

    {% if service_list %}
    <ul>

      {% for serv in service_list %}
      <li>
        <a href="{{ serv.get_absolute_url }}">{{ serv.description }}</a> ({{serv.cost}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Service list is empty.</p>
    {% endif %}
    {% if perms.main.can_service_work %}
    <a href="{% url 'services' %}create">Create service</a>
    {% endif %}
{% endblock %}